### ISSUE TITLE
[Feature]Instructions in "Step 4: Pull your image" are too unfriendly for some learners

### ISSUE THREAD

**Issue by nshun583** [skills/publish-packages#13]
**Is your feature request related to a problem? Please describe.**

`Step 4: Pull your image` asks learners to do the following even before `Activity` part

1. Open your terminal (Bash or Git Bash recommended)
1. Use the following command to log in:
    ```
    docker login docker.pkg.github.com -u USERNAME -p TOKEN
    ```
but this seems to be too unfriendly for some learners because
* all tutorials so far in [GitHub Skills](https://skills.github.com) starting from [Introduction to GitHub](https://github.com/skills/introduction-to-github) to [Continuous integration](https://github.com/skills/continuous-integration) can be completed only in github.com from browsers so learners are not necessarily expected to be familiar working with command-line 
  * this is enough for Windows environment learners to get lost in this step 
* Step 1 explains what Docker is, but does not explain how to install / prepare Docker Engine ready to be used in later steps 

**Describe the solution you'd like**
* Add Step 0 to this tutorial course which points out external guide for
  * introductory resource to help understand command line, especially for Windows learners
  * installing and setting up Docker Engine for later steps
     * https://docs.docker.com/engine/install/
* quick explanation regarding the difference between Docker Desktop and Docker Engine will also help learners

**Describe alternatives you've considered**
* If aforementioned external guide addition cannot be made soon, instead prerequisite section must be at least added to the top of this course to clarify learners already be ready with basic command line operation and Docker Engine installation
  * but this does not solve the root problem of course difficulty level is too suddenly elevated compared to previous [Continuous integration](https://github.com/skills/continuous-integration)

**Additional context**
None

**Comment by mjbear** [comment]
@nshun583 
@hectorsector 

Created PR #49
