### ISSUE TITLE
[Bug] Using deprecated input for docker/build-push-action@v1

### ISSUE THREAD

**Issue by chadfawcett** [skills/publish-packages#17]
**Describe the bug**
During testing of the course I noticed there was a warning annotation saying the workflow is using a deprecated input for `docker/build-push-action@v1`

**To Reproduce**
1. Get to step 4 in the course
2. Click on **Actions** in the top nav
3. Select the latest run of **Publish to docker**
4. Scroll down to Annotations
5. See warning

**Expected behavior**
A workflow run without warning/error annotations

**Screenshots**
<img width="680" alt="Screen Shot 2023-02-15 at 3 14 49 PM" src="https://user-images.githubusercontent.com/3250463/219214226-2e32cedf-2cfb-4e96-9234-2d14f520f982.png">

**Device information**
 - Type: MacBook Pro
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: Version 109.0.5414.87 (Official Build) (x86_64)

**Additional context**
Workflow should probably be updated to use `docker/build-push-action@v2`

**Comment by sinsukehlab** [comment]
I have bumped docker/build-push-action@v1 to v3 in my PR #7 (df35711).
Now v4 is available.
If you have any suggestion about the workflow template, please give me some advice.

**Comment by chadfawcett** [comment]
@sinsukehlab I appreciate the effort! I think #7 should just be kept to your README changes though. We don't want to add too many different things to that one PR. Definitely feel free to open a separate PR with the changes necessary to resolve this issue though.

I'm going to try bumping some of my colleagues to see if we can get the README changes merged.

**Comment by sinsukehlab** [comment]
I have now opened a separate PR #19.
