### ISSUE TITLE
[Bug] Misleading instruction

### ISSUE THREAD

**Issue by hectorsector** [skills/publish-packages#40]
**Describe the bug**
Misleading instruction at https://github.com/skills/publish-packages#keyboard-activity-pull-your-image
The current highlighted docker image location should be removed, because student might just copy and paste.

**To Reproduce**
1. Perform all the previous activities

**Expected behavior**
Additional instruction to lead student to locate the uploaded package, and copy the correct pull script. 

**Screenshots**
For example, 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/42864823/182511239-fba21e00-f02a-43a3-887c-5673927a1c14.png">

_Originally opened in:_ https://github.com/github/skills/issues/72 (internal link only)

**Comment by mjbear** [comment]
@hectorsector 
I guess this one for [Step 4](https://github.com/skills/publish-packages/blob/main/.github/steps/4-pull-your-image.md) is still open and hasn't had a PR merged without referencing this issue ticket.

Question: The student would have to intentionally type out the incorrect package path, right?

I found the screenshots somewhat helpful, however detailed written steps are probably fine too.

**Comment by mjbear** [comment]
@hectorsector :sunglasses: 
Submitted PR #51
