### ISSUE TITLE
[magisk_log_2024-05-21T18.01.37.log](https://github.com/skills/.github/files/15388713/magisk_log_2024-05-21T18.01.37.log)

### ISSUE THREAD

**Issue by dxkf177** [skills/publish-packages#41]
[magisk_log_2024-05-21T18.01.37.log](https://github.com/skills/.github/files/15388713/magisk_log_2024-05-21T18.01.37.log)
[magisk_log_2024-05-21T18.43.14.log](https://github.com/skills/.github/files/15388716/magisk_log_2024-05-21T18.43.14.log)

_Originally posted by @dxkf177 in https://github.com/skills/.github/discussions/569#discussioncomment-9506893_

**Comment by hectorsector** [comment]
Hello there, I'm not sure what this issue is about so if you're having some trouble, please provide some context and open a new issue. Thank you!
