### ISSUE TITLE
[Feature] Distinguish difference between personal (classic) access tokens and fine-grained access tokens

### ISSUE THREAD

**Issue by pvcasillasg** [skills/publish-packages#42]
Hey there, in the step to create a personal access token, you should update it to the fine-grained tokens!

Loving this course!

**Comment by nguyenalex836** [comment]
@pvcasillasg Hello! 👋 Thank you for taking the time to open an issue!

> Hey there, in the step to create a personal access token, you should update it to the fine-grained tokens!

Can you elaborate more on what you mean here? We're glad you are enjoying the course! ✨

**Comment by pvcasillasg** [comment]
> @pvcasillasg Hello! 👋 Thank you for taking the time to open an issue!
> 
> > Hey there, in the step to create a personal access token, you should update it to the fine-grained tokens!
> 
> Can you elaborate more on what you mean here? We're glad you are enjoying the course! ✨

It's kinda weird, but i have never use a personal access token, and I spend some minutes trying to look for those permisions, so maybe you should update the permissions that requiere to set a fine grainer access token.

or just specify which type of access token are you referring in the step, something like this: [Pull Request #43](https://github.com/skills/publish-packages/pull/43)

Just for the most newbies that never did something like that before!

**Comment by nguyenalex836** [comment]
@pvcasillasg Gotcha! Really appreciate the elaboration here 💛 I'll have the review this - thanks again for flagging!

**Comment by pvcasillasg** [comment]
> @pvcasillasg Gotcha! Really appreciate the elaboration here 💛 I'll have the review this - thanks again for flagging!

Thanks to you to take my consideration!

**Comment by mjbear** [comment]
Based on the written steps and screenshot the only token type that fits is the **personal (classic) access tokens**.
That said the content could call the token type out clearly to eliminate confusion.

**Comment by mjbear** [comment]
@pvcasillasg 
I opened up PR #50 to add details.
I'm not sure why your PR got closed, but maybe you needed to fork this repo, create changes, and submit a PR against this repo.

@nguyenalex836 @hectorsector 
This one is in your court now. :laughing: :basketball:

**Comment by hectorsector** [comment]
💟 Thanks so much for the PR @mjbear and for the feedback for all other folks involved. 

> Based on the written steps and screenshot the only token type that fits is the personal (classic) access tokens. That said the content could call the token type out clearly to eliminate confusion.

I agree with you, here. Although the course could benefit from an update in which type of token is used, we can at least make the steps clearer.

**Comment by mjbear** [comment]
> 💟 Thanks so much for the PR @mjbear and for the feedback for all other folks involved.
> 
> > Based on the written steps and screenshot the only token type that fits is the personal (classic) access tokens. That said the content could call the token type out clearly to eliminate confusion.
> 
> I agree with you, here. Although the course could benefit from an update in which type of token is used, we can at least make the steps clearer.

Agree, [fine grained-tokens](https://github.blog/security/application-security/introducing-fine-grained-personal-access-tokens-for-github/) are likely the future ... and likely what many of us will prefer to use. :heart:
